/*
* Public Class TestCreateRelatedRecords{
//	Public static void Function1(List<Account> TriggerRecords){
//		List<Opportunity> opty = New List<Opportunity>();
//		system.debug('all rec: '+ TriggerRecords);
 //       List<Account> AcctRecs = [SELECT Id, (SELECT Id, Name FROM Opportunities) FROM Account where id IN :TriggerRecords];
//        for(Account ActRec: AcctRecs){
//			
//            System.debug('.get(a.Id).Opportunities.size():'+ AcctRecs.get(ActRec.Id).Opportunities.size());
//           
//		}
//	}
//}
*/
Public Class TestCreateRelatedRecords{
}